# Build and run tests inside the docker container
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
# copy the contents of agent working directory on host to workdir in container
COPY . ./
# dotnet commands to build, test, and publish
RUN dotnet restore
RUN dotnet build -c Release
RUN dotnet test BuyService.Tests/BuyService.Tests.csproj -c Release --logger "trx;LogFileName=testresults.trx"
RUN dotnet publish -c Release -o out
ENTRYPOINT ["dotnet", "BuyService.dll"]